### ISSUE TITLE
No Colspan & Rowspan in Table 

### ISSUE THREAD

**Issue by Spepardy** [DavBfr/dart_pdf#256] opened 2020-03-27 21:49 UTC
I couldn't find colspan and rowspan in which I could merge multiple columns into one as well as merging multiple rows as one in table. 
Thank you.

**Comment by DavBfr** [comment] 2020-03-28 14:55
You're right, it's not implemented.

**Comment by DavBfr** [comment] 2020-03-28 15:18
It's not supported on flutter

**Comment by DavBfr** [comment] 2020-03-28 15:25
Duplicate of #167

**Closed** 2020-03-28 15:25 UTC
Labels: enhancement, wontfix

**Comment by Spepardy** [comment] 2020-03-30 23:28
Okay, thanks.
