### ISSUE TITLE
Latex generated PDFs don´t get rendered fully

### ISSUE THREAD

**Issue by Y0ngg4n** [DavBfr/dart_pdf#771] opened 2021-08-07 12:12 UTC
**Describe the bug**
When i import Latex generated PDFs they don´t show Text. (Probably because Latex uses PDF Layers)

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
List<ui.Image> images = List.empty(growable: true);
                    List<Uint8List> imageDataList = List.empty(growable: true);
                    await for (var page in Printing.raster(filePickerCross!.toUint8List(), dpi: 300)) {
                      Uint8List imageBytes = await page.toPng();
                      imageBytes = ImageUtils.resizeImage(imageBytes, 2);
                      final ui.Codec codec = await PaintingBinding.instance!
                          .instantiateImageCodec(imageBytes);
                      final ui.FrameInfo frameInfo = await codec.getNextFrame();
                        images.add(frameInfo.image);
                      imageDataList.add(imageBytes);
                    }
```

**Expected behavior**
It should show all PDF Layers.

**Screenshots**
![Screenshot_18](https://user-images.githubusercontent.com/30302975/128599696-eff1a281-50d6-4094-927a-881abd39613e.png)
As you can see the Text in the Table does not appear.

**Flutter Doctor**

```
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale de_DE.UTF-8)
    • Flutter version 2.2.3 at /home/yonggan/snap/flutter/common/flutter
    • Framework revision f4abaa0735 (vor 5 Wochen), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/yonggan/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /home/yonggan/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.2)
    • Android Studio at /home/yonggan/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at /home/yonggan/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/211.7628.21
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7665

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at /home/yonggan/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/212.4746.92
    • Flutter plugin version 58.0.4
    • Dart plugin version 212.4746.57

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Linux

! Doctor found issues in 1 category.
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [ ] Browser
 - [ ] Windows
 - [x] Linux
 Other not tested but seems to be same behavior.

**Comment by DavBfr** [comment] 2021-08-07 12:41
Duplicate of  #623

**Closed by DavBfr** 2021-08-07 12:41 UTC
Labels: bug, needs triage
