### ISSUE TITLE
Kurdish Characters not rendering correctly

### ISSUE THREAD

**Issue by ArinFaraj** [DavBfr/dart_pdf#480] opened 2020-11-25 04:31 UTC
Thanks for this awesome package 
I have a problem with writing Kurdish characters using pdf package. (Central-Kurdish in windows langs.) 
I'm aware of the Arabic fix that got implemented and it works great for Arabic characters and even Persian chars but for Kurdish, we have some characters missing like **'ڵ ۆ ڕ ێ ...'**
and I thought it might be an easy fix if just add the character Unicodes to the PdfArabic class but the problem is Kurdish characters don't have proper Unicodes and they are not separated as you see in Arabic and Persian 
for example, I will demonstrate with Arabic **ل** and Kurdish **ڵ**
![image](https://user-images.githubusercontent.com/13029655/100180690-bb537a80-2ee9-11eb-9588-b1f6d9b06713.png)
as you can see Arabic characters have separate Unicodes for each situation but the Kurdish characters don't have a unique UTF-16 int bound to it, you can't even find them using Windows Character Map you have to explore the Glyphs of a Kurdish font to find out that they are all part of the same Unicode with a suffix like **uni06B5.init**, **uni06B5.fina** 
their Unicode value is -1 and their Glyph name is as mentioned above.
Used [FontForge](https://fontforge.org) app to explore glyphs of [Rabar_021.tff](https://github.com/DavBfr/dart_pdf/files/5594331/Rabar_021.zip) font which is mainly a unicode kurdish font.

I'm aware that this issue is not the fault of this package but I was hoping to get some help for fixing this issue.
the Kurdish language is perfectly fine in flutter widgets I just couldn't find a way to write these characters in an int format.

a workaround might be to use repaintBoundary widget to screenshot a widget and insert it as an image but I was hoping to find a solution before I go there.

sorry for not including other parts of a bug report but I thought it might not need them as we already know the issue with the Arabic language and how to fix it

**Comment by DavBfr** [comment] 2020-11-25 10:43
I think this is another issue linked to  #198 that has to be read from the font file.

**Comment by ArinFaraj** [comment] 2020-11-25 11:17
Thanks a lot 
I didn't give much attention to that issue but apparently its the same problem
I'm gonna give it a try and hopefully fix the issue

**Comment by DavBfr** [comment] 2021-05-08 12:10
Duplicate of #198

**Closed by DavBfr** 2021-05-08 12:10 UTC
Labels: enhancement, help wanted

**Comment by hussenIbrahim** [comment] 2021-07-26 10:44
> Thanks a lot
> I didn't give much attention to that issue but apparently its the same problem
> I'm gonna give it a try and hopefully fix the issue

Slaw
did you fix the issue ?

**Comment by ArinFaraj** [comment] 2021-07-26 23:38
> > Thanks a lot
> > I didn't give much attention to that issue but apparently its the same problem
> > I'm gonna give it a try and hopefully fix the issue
> 
> Slaw
> did you fix the issue ?

I was too busy with college so I just made the whole thing in a canvas and turned it into an image then printed the image.
it works fine but if you use plan to build it for web it's going to be really slow cause image compression in dart in general is just horribly slow. also there might be a way to compress efficiently maybe [this](https://github.com/crazecoder/flutter_luban) package but I haven't tried it

**Comment by KozanMelan** [comment] 2023-07-09 11:29
I still facing the same issue, and it is not being solved yet.. any update @ArinFaraj @DavBfr  .. thanks

**Comment by MuhamadHaydar** [comment] 2024-07-30 06:34
The issue has not been solved, it has a rendering issue with these letters.

**Comment by hamreen** [comment] 2025-07-22 21:45
I have solved the problem and published it as a new package called hamreen_printing.
For more details, you can watch the following video, which explains how to print Kurdish letters correctly using this new package:

👉 https://youtu.be/hMOIpvJgKiQ
