### ISSUE TITLE
Flutter 3.0 support

### ISSUE THREAD

**Issue by hs029** [DavBfr/dart_pdf#1051] opened 2022-05-20 13:36 UTC
See this warning:
../../../appdev/flutter/.pub-cache/hosted/pub.flutter-io.cn/printing-5.9.0/lib/src/preview/controller.dart:70:35: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../appdev/flutter/packages/flutter/lib/src/widgets/binding.dart').
    final locale = WidgetsBinding.instance!.window.locale;
                                  ^

**Comment by DavBfr** [comment] 2022-05-20 15:48
Yes, duplicate of #1039 will be release as next version printing-5.9.1

**Closed** 2022-05-20 20:15 UTC
Labels: bug
