### ISSUE TITLE
Compatibility Flutter 1.6

### ISSUE THREAD

**Issue by brux88** [DavBfr/dart_pdf#86] opened 2019-06-08 07:50 UTC
**Describe the bug**
Compatibility with flutter 1.6.0 this error:
 Error: The argument type 'Future<void> Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.

**Comment by DavBfr** [comment] 2019-06-08 12:14
Flutter 1.6 is still not in the stable branch.
This is a duplicate of #81, please follow the instructions in this issue to fix your problem.

**Comment by DavBfr** [comment] 2019-07-11 13:17
Version 2.1 should fix the issue.

**Closed by DavBfr** 2019-07-11 13:17 UTC
