### ISSUE TITLE
Doesn't support RTL text direction with Hebrew.

### ISSUE THREAD

**Issue by ironpotter** [DavBfr/dart_pdf#443] opened 2020-10-06 17:18 UTC
**Describe the bug**
Text widget doesn't support rtl direction with Hebrew. 
Link to font ~> [http://freefonts.co.il/downloads/dana-yad-alefalefalef.zip](url)

**To Reproduce**
Code snippet to reproduce the behavior:
```
    final pw.Document doc = pw.Document();
    final font = await rootBundle.load("assets/fonts/VarelaRound-Regular.ttf");
    final ttf = pw.Font.ttf(font);

    doc.addPage(
      pw.Page(
        theme: pw.ThemeData.withFont(
          base: ttf,
        ),
        build: (pw.Context context) =>
            pw.Text('שלום', textDirection: pw.TextDirection.rtl),
      ),
    );
    return doc.save();
```

**Full code**

```
import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:pdf/pdf.dart';
import 'package:printing/printing.dart';
import 'package:pdf/widgets.dart' as pw;

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
          body: Container(
        margin: EdgeInsetsDirectional.only(top: 50),
        child: PdfPreview(
          build: (format) => generateDocument(format),
        ),
      )),
    );
    return PdfPreview(
      build: (format) => generateDocument(format),
    );
  }

  Future<Uint8List> generateDocument(PdfPageFormat format) async {
    final pw.Document doc = pw.Document();
    final font = await rootBundle.load("assets/fonts/VarelaRound-Regular.ttf");
    final ttf = pw.Font.ttf(font);

    doc.addPage(
      pw.Page(
        theme: pw.ThemeData.withFont(
          base: ttf,
        ),
        build: (pw.Context context) =>
            pw.Text('שלום', textDirection: pw.TextDirection.rtl),
      ),
    );
    return doc.save();
  }
}

```

**Expected behavior**
![what_expect](https://user-images.githubusercontent.com/32612877/95237165-8a6f9700-0810-11eb-9caa-07d6a7653140.jpg)

**Screenshots**
It get 'םולש" instead "שלום"
![what_i_get](https://user-images.githubusercontent.com/32612877/95237242-9eb39400-0810-11eb-975a-f851c23493db.jpg)

**Flutter Doctor**
[✓] Flutter (Channel beta, 1.22.0-12.2.pre, on Linux, locale en_IL)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] Connected device (3 available)

**Comment by DavBfr** [comment] 2020-10-10 10:55
Sorry, I don't know how Hebrew works, someone else will have to fix this.

**Comment by MstrZeroOne** [comment] 2020-10-12 07:48
I have the same problem with the Persian language.

**Comment by MstrZeroOne** [comment] 2020-10-19 05:03
I solved my problem with the Directionality widget. By setting direction: TextDirection.rtl.

**Comment by DavBfr** [comment] 2021-05-08 12:09
Duplicate of #198

**Closed by DavBfr** 2021-05-08 12:09 UTC
Labels: enhancement, help wanted
