### ISSUE TITLE
ttf fonts issue

### ISSUE THREAD

**Issue by feemagdev** [DavBfr/dart_pdf#736] opened 2021-06-24 06:01 UTC
**Describe the bug**

When i create a pdf with ttf fonts. its written in characters not words  in pdf.
**To Reproduce**
Code snippet to reproduce the behavior:
```dart
// your code
```
  void _getMonthlyList() async {
    var myTheme = pw.ThemeData.withFont(
      base: pw.Font.ttf(
        await rootBundle
            .load("assets/fonts/Jameel-Noori-Nastaleeq-Kasheeda.ttf"),
      ),
    );
    Hive.openBox<KhataBanam>('khata_banam').then((value) {
      final doc = pw.Document(pageMode: PdfPageMode.outlines, theme: myTheme);
      final dealerKhata = value.values.where(
          (element) => element.dealerID == _selectedDealer!.key.toString());
      int startYear = _selectedDate!.year;
      int startMonth = _selectedDate!.month;
      int startDay = 19;
      int endYear = _selectedDate!.year;
      int endMonth = _selectedDate!.month;
      int endDay = 20;
      if (_selectedDate!.month == 1) {
        startYear = _selectedDate!.year - 1;
        startMonth = 12;
      } else {
        startMonth = startMonth - 1;
      }

      DateTime startDate = DateTime(startYear, startMonth, startDay);
      DateTime endDate = DateTime(endYear, endMonth, endDay);
      final List<KhataBanam> khataBanamList = [];

      dealerKhata.forEach((element) {
        DateTime compareDate = DateTime(element.dateTime.year,
            element.dateTime.month, element.dateTime.day);
        if (compareDate.isAfter(startDate) &&
            compareDate.isBefore(endDate) &&
            element.totalBlocks != 0) {
          khataBanamList.add(element);
        }
      });

      doc.addPage(pw.Page(
          pageFormat: PdfPageFormat.a4,
          build: (context) {
            final data = khataBanamList
                .map((KhataBanam value) => [
                      DateFormat.yMMMd('UR').format(value.dateTime),
                      value.detail,
                      value.totalBlocks,
                      value.namkeenBlocks
                    ])
                .toList();

            final headers = ['تاريخ'];

            return pw.Table.fromTextArray(headers: headers, data: data);
          }));
      doc.save().then((value) async {
        final dir = await getApplicationDocumentsDirectory();
        String name = 'faheem.pdf';
        final file = File('${dir.path}/$name');
        file.writeAsBytes(value);
        final url = file.path;
        OpenFile.open(url);
      });
    });
  }
}
**Expected behavior**

see header string. i also put screen shot of that string. also the see the 1st column the month is also in charcaters not in words of urdu. I tried different ttf urdu and arabic fonts. same happens.

**Screenshots**

![image](https://user-images.githubusercontent.com/63182768/123210451-745b5100-d4db-11eb-8b60-fcdc417f5404.png)

**Flutter Doctor**

```
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [ ] Browser
 - [x] Windows
 - [ ] Linux
Windows
**Smartphone (please complete the following information):**

**Additional context**

**Comment by DavBfr** [comment] 2021-06-25 11:15
Duplicate of #198

**Closed** 2021-06-25 11:16 UTC
Labels: enhancement
