### ISSUE TITLE
Exception when using maxLines property with RichText pdf component

### ISSUE THREAD

**Issue by saidlp** [DavBfr/dart_pdf#500] opened 2020-12-18 09:57 UTC
Hi Dav, and thanks a lot for coming up with such helpful libraries!

But nothing being perfect in this world, I still managed to run into a little issue it seems like: when using the maxLines property of your RichText pdf component, it triggered the following exception:

`[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: RangeError (start): Invalid value: Not in inclusive range 0..8: 12
#0      RangeError.checkValidRange (dart:core/errors.dart:352:7)
#1      List.sublist (dart:core-patch/growable_array.dart:84:38)
#2      RichText.layout (package:pdf/widgets/text.dart:784:18)
#3      Flex.layout (package:pdf/widgets/flex.dart:288:15)
#4      Padding.layout (package:pdf/widgets/basic.dart:84:13)
#5      SingleChildWidget.layout (package:pdf/widgets/widget.dart:170:13)
#6      ConstrainedBox.layout (package:pdf/widgets/basic.dart:420:13)
#7      StatelessWidget.layout (package:pdf/widgets/widget.dart:134:14)
#8      Flex.layout (package:pdf/widgets/flex.dart:288:15)
#9      Flex.layout (package:pdf/widgets/flex.dart:288:15)
#10     Page.layout (package:pdf/widgets/page.dart:183:11)
#11     Page.postProcess (package:pdf/widgets/page.dart:125:31)
#12     Document.save (package:pdf/widgets/document.dart:72:14)
`

the debugger took me to package:pdf/widgets/text.dart:784:18

`          _spans.sublist(spanStart),
`

where _spans list seems to have been truncated due to maxLines property, and spanStart index seems to be positioned as if the list hadn't been truncated.

Kind regards

**Comment by DavBfr** [comment] 2020-12-18 11:39
Can you post an example code that reproduces the issue, and the version of the library you use?

**Comment by saidlp** [comment] 2020-12-18 13:38
Hi again Dav!
I'm using version pdf: ^1.12.0

**Comment by saidlp** [comment] 2020-12-18 14:18
here comes the extract from the code that triggers the exception:

`   eventWidgetList.add(pdfWidget.RichText(
/*      maxLines: 2,   */
      text: pdfWidget.TextSpan(
        style: currentBlock.activities.length == 1? activityStyle : activitiesListStyle,
        children: buildActivitiesSummaryItemsListForPdf(currentBlock),
      ), ));
` 

with `maxLines: 2,` commented out, it works like a charm. Remove the comments, and bang (assuming the surrounding elements limits the width so that the RichText will have to wrap on more that 2 lines).

My code is a bit (over?)complicated so right now, I can't easily post more than an extract as I did. If it helps, I can try to create a mini code snippet that reproduces the problem, but as my coming weeks looks like, it might only come in 2021 ;)

**Comment by DavBfr** [comment] 2020-12-18 19:32
Ok, I can't reproduce with this:

```dart

import 'dart:io';
import 'dart:math' as math;

import 'package:pdf/widgets.dart';

void main() {
  final pdf = Document();
  final rnd = math.Random(42);
  final para = LoremText(random: rnd).paragraph(300);

  pdf.addPage(
    Page(
      build: (Context context) => RichText(
        maxLines: 3,
        text: TextSpan(
          text: para,
        ),
      ),
    ),
  );

  final file = File('test.pdf');
  file.writeAsBytesSync(pdf.save());
}
```

**Comment by saidlp** [comment] 2020-12-18 21:01
To trigger the exception, we need to add a "children:" field to the TextSpan.
Example:

Prepare a fairly long list of TextSpan elements        
` 
List<pdfWidget.TextSpan> spans = List<pdfWidget.TextSpan>();
                    for (int i = 0; i < 150; i++) {
                      spans.add(pdfWidget.TextSpan(text: "Value$i"));
                    }`

 use the list as children in our RichText
`
                    pdfDocTest.addPage(
                      pdfWidget.Page(
                        build: (pdfWidget.Context context) => pdfWidget.RichText(
             //             maxLines: 3,
                          text: pdfWidget.TextSpan(
                            text: para,
                            children: spans
                          ),
                        ),
                      ),
                    );`

Then I do get an exception

**Comment by DavBfr** [comment] 2020-12-18 21:43
Should be fixed in the master branch.

**Comment by saidlp** [comment] 2020-12-19 05:46
Great job Dav, and impressive reactivity.
Have a merry Chrismas, and best wishes for 2121!

**Comment by DavBfr** [comment] 2020-12-19 11:10
Thanks, you as well!
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).

**Closed by DavBfr** 2020-12-19 11:10 UTC
Labels: bug

**Comment by saidlp** [comment] 2020-12-19 15:34
I did 😊
