### ISSUE TITLE
Error with unicode characters

### ISSUE THREAD

**Issue by apps-transround** [DavBfr/dart_pdf#77] opened 2019-05-22 14:53 UTC
**Describe the bug**
Error when adding text with non-latin1 characters:
I/flutter (16985): #0      _UnicodeSubsetEncoder.convert (dart:convert/ascii.dart:86:9)
I/flutter (16985): #1      Latin1Codec.encode (dart:convert/latin1.dart:40:46)
I/flutter (16985): #2      PdfFont.stringMetrics (package:pdf/src/font.dart:141:36)
I/flutter (16985): #3      RichText.layout.<anonymous closure> (package:pdf/widgets/text.dart:196:20)
I/flutter (16985): #4      TextSpan.visitTextSpan (package:pdf/widgets/text.dart:82:19)
I/flutter (16985): #5      RichText.layout (package:pdf/widgets/text.dart:177:10)
I/flutter (16985): #6      MultiPage.generate (package:pdf/widgets/multi_page.dart:186:13)
I/flutter (16985): #7      Document.addPage (package:pdf/widgets/document.dart:56:10)
...

**To Reproduce**
Paragraph(text:  'őú'),

**Additional context**
1.3.10
Probably all latin1.encode calls should be replaced to utf8.encode in font.dart?
Doing that prevents the error, pdf is created but multi-byte characters are not rendered well.

**Comment by DavBfr** [comment] 2019-05-25 11:43
Duplicate of #76

**Closed** 2019-05-25 22:47 UTC
