### ISSUE TITLE
Thai font pdf display incorrect

### ISSUE THREAD

**Issue by cchaiyatad** [DavBfr/dart_pdf#339] opened 2020-06-18 08:36 UTC
**Describe the bug**
I try to generate pdf with Thai language but it not work correctly 
font that I use is [google Sarabun font](https://fonts.google.com/specimen/Sarabun?subset=thai) 

**Expected behavior**
The output expected to be ท่ี หมู่ คุก กฤษฏิ์ การันต์

**Screenshots**
<img width="359" alt="Screen Shot 2020-06-18 at 11 14 08 AM" src="https://user-images.githubusercontent.com/30238194/84997236-7f68fc00-b178-11ea-9849-86c6c9d4176a.png">
In first line first word is happen when I type ี before ่ and the second word is ู before ่
In second line first word is happen when I type ่ before ี and the second word is ่ before ู

**Flutter Doctor**
```
Downloading android-arm-profile/darwin-x64 tools...                 1.4s
Downloading android-arm-release/darwin-x64 tools...                 1.1s
Downloading android-arm64-profile/darwin-x64 tools...               1.0s
Downloading android-arm64-release/darwin-x64 tools...               1.0s
Downloading android-x64-profile/darwin-x64 tools...                 1.0s
Downloading android-x64-release/darwin-x64 tools...                 1.0s
[✓] Flutter (Channel beta, 1.19.0-4.1.pre, on Mac OS X 10.15.5 19F101, locale en)
    • Flutter version 1.19.0-4.1.pre at /Users/cchaiyatad/Library/flutter
    • Framework revision f994b76974 (8 days ago), 2020-06-09 15:53:13 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/cchaiyatad/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.106

• No issues found!
```

**Desktop (please complete the following information):**
 - [*] Browser

**Additional context**
I think this problem is similar to #198 and #336

**Comment by DavBfr** [comment] 2021-05-08 12:10
Duplicate of #198

**Closed by DavBfr** 2021-05-08 12:10 UTC
Labels: enhancement, help wanted
