### ISSUE TITLE
Marathi text not rendering correctly

### ISSUE THREAD

**Issue by ashutosh1211** [DavBfr/dart_pdf#336] opened 2020-06-14 01:39 UTC
I have tried various fonts which are widely used in indic scripts.
Compound words are not working properly.

Expected:
अनन्न

Current Output:
![image](https://user-images.githubusercontent.com/4639147/84582755-c1f3a700-ae0d-11ea-9205-a1e719792282.png)

**Comment by DavBfr** [comment] 2020-06-14 10:50
duplicate #198

**Comment by ashutosh1211** [comment] 2020-06-21 09:59
@DavBfr  Im able to parse all tables in GSUB, Script , Features and Lookups. 

DO you have any idea on substitution?
Im currently trying to support Beng, Deva, Gujr, Guru, Knda, Mlym, Mtei, Olck, Orya, Sinh, Sora, Taml, Telu these indic languages
Looks like substitution is complex for these languages.

**Comment by DavBfr** [comment] 2020-06-21 11:18
@ashutosh1211 Can I look at the code?

**Comment by ashutosh1211** [comment] 2020-06-21 12:19
@DavBfr 
I have written some intermediate code for substitution. I'll push the code in some time.
If I'm correct you have not written any code for processing ligatures ? Right? Arabic branch does not have that functionality.

**Comment by DavBfr** [comment] 2020-06-21 12:33
Yes, the Arabic branch uses a dedicated substitution algorithm.

**Comment by ashutosh1211** [comment] 2020-06-21 23:05
@DavBfr  You can check the parsing code in this repository
https://github.com/ashutosh1211/dart_pdf

What i was doing is porting javascript code of opentype.js into dart for substitution but still not able to successfully create pdf with these changes.

**Comment by ashutosh1211** [comment] 2020-06-22 18:18
Hi @DavBfr can you help me writing further code in this repo https://github.com/ashutosh1211/dart_pdf for supporting indic languages.

**Comment by ab-dev-github** [comment] 2020-10-26 07:28
> I have tried various fonts which are widely used in indic scripts.
> Compound words are not working properly.
> 
> Expected:
> अनन्न
> 
> Current Output:
> ![image](https://user-images.githubusercontent.com/4639147/84582755-c1f3a700-ae0d-11ea-9205-a1e719792282.png)

Which font did you use to get this?

**Comment by ashutosh1211** [comment] 2020-10-28 16:39
> > I have tried various fonts which are widely used in indic scripts.
> > Compound words are not working properly.
> > Expected:
> > अनन्न
> > Current Output:
> > ![image](https://user-images.githubusercontent.com/4639147/84582755-c1f3a700-ae0d-11ea-9205-a1e719792282.png)
> 
> Which font did you use to get this?

Nato Sans font.

https://fonts.google.com/specimen/Noto+Sans?subset=devanagari

**Comment by pluzmedia** [comment] 2021-01-07 14:00
> > > I have tried various fonts which are widely used in indic scripts.
> > > Compound words are not working properly.
> > > Expected:
> > > अनन्न
> > > Current Output:
> > > ![image](https://user-images.githubusercontent.com/4639147/84582755-c1f3a700-ae0d-11ea-9205-a1e719792282.png)
> > 
> > 
> > Which font did you use to get this?
> 
> Nato Sans font.
> 
> https://fonts.google.com/specimen/Noto+Sans?subset=devanagari

Have you completed it?

**Comment by mirkarpude** [comment] 2021-03-24 11:49
any update on this?

**Comment by DavBfr** [comment] 2021-05-08 12:11
Duplicate of #198

**Closed by DavBfr** 2021-05-08 12:11 UTC
Labels: enhancement, help wanted

**Comment by niraj8763** [comment] 2024-09-30 14:54
any solution is there
