### ISSUE TITLE
Thai font style with 3 level, causes overflowing

### ISSUE THREAD

**Issue by GuvanchBayryyyev** [DavBfr/dart_pdf#658] opened 2021-04-27 02:22 UTC
**Describe the bug**

When I want to print the thai language document, the characters of alphabet overflows each other
**To Reproduce**
Code snippet to reproduce the behavior:
```dart
pw.Text('นี้')
```

**Expected behavior**

Expected to have those 3 level alphabets being separated, as shown in screenshot
<img width="28" alt="Screen Shot 2564-04-29 at 09 18 48" src="https://user-images.githubusercontent.com/35362686/116494851-e9d7e600-a8cb-11eb-82d3-c4f986fc40b6.png">

**Actual behavior**
<img width="11" alt="Screen Shot 2564-04-29 at 09 20 55" src="https://user-images.githubusercontent.com/35362686/116494966-358a8f80-a8cc-11eb-89bd-3c2e9260ec9b.png">

**Comment by DavBfr** [comment] 2021-05-08 12:09
Duplicate of #198

**Closed by DavBfr** 2021-05-08 12:09 UTC
Labels: bug, needs triage

**Comment by aunzo** [comment] 2022-04-10 04:28
> Duplicate of #198

this is not work for sarabun font.

**Comment by nutjaa** [comment] 2022-08-30 05:56
@GuvanchBayryyyev I got same issue. Did u solve yet?

**Comment by Blue-Cheesecake** [comment] 2024-11-02 13:32
@GuvanchBayryyyev  I also have this issue. Is there any solution for this?
