### ISSUE TITLE
Using pw.Text inside a pw.Column with softWrap & overflow span is not working

### ISSUE THREAD

**Issue by rohansohonee** [DavBfr/dart_pdf#930] opened 2022-02-01 15:18 UTC
Hi

I have query regarding the use of pdf pw.Text widget when used inside the pw.Column widget. I am using the text widget properties `softWrap` & `overflow span`, here is code snippet:
```dart
// text widget inside the column
// gives the Exception: This widget created more than 20 pages. This may be an issue in the widget or the document. 
document.addPage(
      pw.MultiPage(
        pageFormat: format,
        build: (context) {
          return [
            pw.Column(
              children: [
                pw.Text(
                  'test' * 3000,
                  softWrap: true,
                  overflow: pw.TextOverflow.span,
                ),
              ],
            ),
          ];
        },
      ),
    );

    return document.save();


// without using the column is working fine
document.addPage(
      pw.MultiPage(
        pageFormat: format,
        build: (context) {
          return [
            pw.Text(
              'test' * 3000,
              softWrap: true,
              overflow: pw.TextOverflow.span,
            ),
          ];
        },
      ),
    );

    return document.save();
```

The pw.Column widget extends the Flex which is using "with SpanningWidget", so the column should span it's children to the next page right?

Please let me know if there is a solution.

**Comment by deepak786** [comment] 2022-02-02 13:05
@DavBfr any solution to this?

**Comment by DavBfr** [comment] 2022-02-05 14:18
Duplicate of #684

**Closed by DavBfr** 2022-02-05 14:18 UTC
Labels: support, needs triage
