### ISSUE TITLE
import 'package:printing/printing.dart' got error

### ISSUE THREAD

**Issue by kiko555** [DavBfr/dart_pdf#84] opened 2019-06-03 15:28 UTC
**Describe the bug**
after import 'package:printing/printing.dart'
run on android get the error:

file:///Users/development/flutter/.pub-cache/hosted/pub.dartlang.org/printing-2.0.3/lib/src/asset_utils.dart:49:27: Error: The argument type 'Future<void> Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'Future' is from 'dart:async'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('file:///Users/development/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:///Users/development/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
    stream.removeListener(listener);

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
import 'dart:async';
import 'package:flutter/material.dart';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as Pdf;
import 'package:printing/printing.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Printing Demo'),
        ),
        floatingActionButton: FloatingActionButton(
          child: const Icon(Icons.print),
          tooltip: 'Print Document',
          onPressed: () {
            Printing.layoutPdf(onLayout: buildPdf);
          },
        ),
        body: Center(child: const Text('Click on the print button below')),
      ),
    );
  }

  List<int> buildPdf(PdfPageFormat format) {
    final PdfDoc pdf = PdfDoc()
      ..addPage(Pdf.Page(
          pageFormat: format,
          build: (Pdf.Context context) {
            return Pdf.ConstrainedBox(
              constraints: const Pdf.BoxConstraints.expand(),
              child: Pdf.FittedBox(
                  child: Pdf.Text(
                'Hello World',
              )),
            );
          }));
    return pdf.save();
  }

}

```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [X] Android
 - [ ] Browser

**Comment by DavBfr** [comment] 2019-06-03 21:01
This is a duplicate of #81, please follow the instructions in this issue to fix your problem.

**Closed by DavBfr** 2019-06-03 21:01 UTC
