### ISSUE TITLE
Windows build issue

### ISSUE THREAD

**Issue by selvam920** [DavBfr/dart_pdf#646] opened 2021-04-20 07:58 UTC
CMake Error at flutter/ephemeral/.plugin_symlinks/printing/windows/DownloadProject.cmake:179 (message):
  Build step for pdfium failed: 1
Call Stack (most recent call first):
  flutter/ephemeral/.plugin_symlinks/printing/windows/CMakeLists.txt:23 (download_project)

Flutter (Channel beta, 2.2.0-10.1.pre, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.2.0-10.1.pre at D:\SW\flutter_master\flutter
    • Framework revision 0941968447 (5 days ago), 2021-04-15 12:01:02 -0700
    • Engine revision d2a2e93510
    • Dart version 2.13.0 (build 2.13.0-211.6.beta)

**Comment by Maged12** [comment] 2021-04-20 10:04
i have the same error 
Flutter 2.0.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b1395592de (3 weeks ago) • 2021-04-01 14:25:01 -0700
Engine • revision 2dce47073a
Tools • Dart 2.12.2
and i upgrade , downgrade and change the channel without any success

**Comment by aihamhasan** [comment] 2021-04-20 10:22
Even am facing the same issue from today, still couldnt build windows

Launching lib\main.dart on Windows in debug mode...
lib\main.dart:1
CMake Error at flutter/ephemeral/.plugin_symlinks/printing/windows/DownloadProject.cmake:179 (message):
  Build step for pdfium failed: 1
Call Stack (most recent call first):
  flutter/ephemeral/.plugin_symlinks/printing/windows/CMakeLists.txt:23 (download_project)


Exception: Unable to generate build files
Exited (sigterm)

**Comment by DavBfr** [comment] 2021-04-20 10:47
Yes, Benoît did not build the windows version on the latest release, so the link does not exist.
see https://github.com/bblanchon/pdfium-binaries/issues/37
You can wait for the next release, or change the file printing/windows/CMakeLists.txt and replace the URL with an existing zip.

**Comment by selvam920** [comment] 2021-04-21 02:41
is there any quick fix, i'm getting below error after changing to below URL
https://github.com/bblanchon/pdfium-binaries/releases/download/chromium%2F4475/pdfium-windows-x64.zip

Exception: No Windows desktop project configured. See https://flutter.dev/desktop#add-desktop-support-to-an-existing-flutter-app to learn about adding Windows support to a project.
Exited (sigterm)

**Comment by harbignote** [comment] 2021-04-23 08:47
I'm Having the same issue here : 

`
CMake Error at flutter/ephemeral/.plugin_symlinks/printing/windows/DownloadProject.cmake:179 (message):
  Build step for pdfium failed: 1
Call Stack (most recent call first):
  flutter/ephemeral/.plugin_symlinks/printing/windows/CMakeLists.txt:23 (download_project)`

**Comment by harbignote** [comment] 2021-04-23 09:07
the issue is fixed by doing this 

change the download path from
:  https://github.com/bblanchon/pdfium-binaries/releases/latest/download/pdfium-windows-${ARCH}.zip 
to https://github.com/bblanchon/pdfium-binaries/releases/download/chromium%2F4475/pdfium-windows-x64.zip 
inside the file  [windows\flutter\ephemeral\.plugin_symlinks\printing\windows\CMakeLists.txt] line  27 

then run > flutter clean > flutter run

**Comment by DavBfr** [comment] 2021-04-23 10:33
Fixed in the master branch.

**Comment by Abanoub-Fouad** [comment] 2021-04-26 12:24
I have the same error
and i upgrade, downgrade and change the channel without any success

**Comment by DavBfr** [comment] 2021-04-26 12:26
Fixed in printing-5.2.0

**Closed by DavBfr** 2021-04-26 12:26 UTC
Labels: bug

**Comment by BangPei** [comment] 2021-08-23 02:56
i have tried in printing -5.5.0 and downgrade to 5.2.0.
still  cannot run my app in windows

**Comment by BangPei** [comment] 2021-08-23 03:27
> the issue is fixed by doing this
> 
> change the download path from
> : [https://github.com/bblanchon/pdfium-binaries/releases/latest/download/pdfium-windows-${ARCH}.zip](https://github.com/bblanchon/pdfium-binaries/releases/latest/download/pdfium-windows-$%7BARCH%7D.zip)
> to https://github.com/bblanchon/pdfium-binaries/releases/download/chromium%2F4475/pdfium-windows-x64.zip
> inside the file [windows\flutter\ephemeral.plugin_symlinks\printing\windows\CMakeLists.txt] line 27
> 
> then run > flutter clean > flutter run

still not working

**Comment by ictekin** [comment] 2021-11-14 23:24
While I was able to run my application on the Windows platform without any problems, I suddenly started encountering this error today. I couldn't find any solution. Will it be developed?

**Comment by hillelcoren** [comment] 2021-11-16 12:44
I'm seeing a similar error with a different project. I think the problem may be that the CMake file tries to download a .zip file but it looks like the repo is now sharing the package as .tgz and using 'win' instead of 'windows'

https://github.com/bblanchon/pdfium-binaries/releases/tag/chromium%2F4648

https://github.com/bblanchon/pdfium-binaries/releases/tag/chromium%2F4706

**Comment by TarekFaysal** [comment] 2022-03-16 10:00
Did anyone solve this issue? I am trying to figure this out. But no luck. Let me know if it can be solved.

**Comment by ahmedevcode** [comment] 2025-03-04 11:55
any solution ??
